[tool.black]
line-length = 120
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 120
length_sort = "False"
length_sort_sections = "stdlib"

[tool.ruff]
# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py312"
line-length = 120
extend-exclude=[
    "__pycache__",
    "build",
    "tools/**",
    ".history",
]
lint.select = [
    "ALL",
]
lint.extend-ignore = [
    "D100", # Missing docstring in public module
    "INP001", # conf.py is part of an implicit namespace package
]


[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.codespell]
skip = "*cache*,*egg*,*extern*,.git,.idea,.tox,_build,*truncated,*.svg,.history"
ignore-words-list = "sav,"
