name: PyData Subdomain
description: Request a <subdomain>.pydata.org for your project website, docs...
labels: ["Request - PyData subdomain"]

body:
  - type: input
    id: project
    attributes:
      label: project
      description: >
        Please provide what NumFOCUS sponsored project you represent
    validations:
      required: true

  - type: checkboxes
    id: is_update
    attributes:
      label: Update existing subdomain?
      options:
        - label: >
            This request is for updating the DNS of an EXISTING subdomain

  - type: input
    id: subdomain
    attributes:
      label: Subdomain
      description: >
        Please provide what subdomain you are requesting (e.g. `pandas` for `pandas.pydata.org`)
    validations:
      required: true

  - type: textarea
    id: dns
    attributes:
      label: DNS
      description: >
        Please provide what DNS records do you need for the subdomain (e.g. `A 8.8.8.8`)
    validations:
      required: true

  - type: textarea
    id: observations
    attributes:
      label: Observations
      description: >
        Please let us know if there is any other information you'd like to provide
    validations:
      required: true
